---

- name: Create user ssh authorized key file
  user:
    name={{ item.name }}
    state=present
    generate_ssh_key=yes
    home={{ item.home | default('/home/' ~ item.name) }}
  with_items: ssh_authorized_keys

- name: Grant ssh rights
  user:
    name={{ item.name }}
    shell={{ item.shell | default('/bin/bash') }}
  with_items: ssh_authorized_keys

- name: Add SSH keys from local
  authorized_key:
     user="{{ item.0.name }}"
     key="{{ lookup('file', item.1) }}"
  with_subelements:
     - ssh_authorized_keys
     - local
